/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ApiFieldError from './ApiFieldError';





/**
* The ApiError model module.
* @module model/ApiError
* @version 1.0.0
*/
export default class ApiError {
    /**
    * Constructs a new <code>ApiError</code>.
    * @alias module:model/ApiError
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ApiError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ApiError} obj Optional instance to populate.
    * @return {module:model/ApiError} The populated <code>ApiError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiError();

            
            
            

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], [ApiFieldError]);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
        }
        return obj;
    }

    /**
    * @member {Number} code
    */
    code = undefined;
    /**
    * @member {Array.<module:model/ApiFieldError>} errors
    */
    errors = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {Number} status
    */
    status = undefined;
    /**
    * @member {Date} timestamp
    */
    timestamp = undefined;








}


