/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ApiFieldError model module.
* @module model/ApiFieldError
* @version 1.0.0
*/
export default class ApiFieldError {
    /**
    * Constructs a new <code>ApiFieldError</code>.
    * @alias module:model/ApiFieldError
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ApiFieldError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ApiFieldError} obj Optional instance to populate.
    * @return {module:model/ApiFieldError} The populated <code>ApiFieldError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ApiFieldError();

            
            
            

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('rejectedValue')) {
                obj['rejectedValue'] = ApiClient.convertToType(data['rejectedValue'], Object);
            }
        }
        return obj;
    }

    /**
    * @member {String} field
    */
    field = undefined;
    /**
    * @member {String} message
    */
    message = undefined;
    /**
    * @member {Object} rejectedValue
    */
    rejectedValue = undefined;








}


