/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ChangeDTO from './ChangeDTO';





/**
* The ChangesDTO model module.
* @module model/ChangesDTO
* @version 1.0.0
*/
export default class ChangesDTO {
    /**
    * Constructs a new <code>ChangesDTO</code>.
    * @alias module:model/ChangesDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ChangesDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ChangesDTO} obj Optional instance to populate.
    * @return {module:model/ChangesDTO} The populated <code>ChangesDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangesDTO();

            
            
            

            if (data.hasOwnProperty('author')) {
                obj['author'] = ApiClient.convertToType(data['author'], 'String');
            }
            if (data.hasOwnProperty('changes')) {
                obj['changes'] = ApiClient.convertToType(data['changes'], {'String': [ChangeDTO]});
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} author
    */
    author = undefined;
    /**
    * @member {Object.<String, Array.<module:model/ChangeDTO>>} changes
    */
    changes = undefined;
    /**
    * @member {Date} date
    */
    date = undefined;
    /**
    * @member {String} id
    */
    id = undefined;








}


