/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PublicKeyDTO model module.
* @module model/PublicKeyDTO
* @version 1.0.0
*/
export default class PublicKeyDTO {
    /**
    * Constructs a new <code>PublicKeyDTO</code>.
    * @alias module:model/PublicKeyDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PublicKeyDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PublicKeyDTO} obj Optional instance to populate.
    * @return {module:model/PublicKeyDTO} The populated <code>PublicKeyDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicKeyDTO();

            
            
            

            if (data.hasOwnProperty('publicKey')) {
                obj['publicKey'] = ApiClient.convertToType(data['publicKey'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} publicKey
    */
    publicKey = undefined;








}


