/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import GeneralDataDTO from './GeneralDataDTO';
import HospitalizationDTO from './HospitalizationDTO';
import MedicationDTO from './MedicationDTO';
import PathologyDTO from './PathologyDTO';





/**
* The EmergencyDataDTO model module.
* @module model/EmergencyDataDTO
* @version 1.0.0
*/
export default class EmergencyDataDTO {
    /**
    * Constructs a new <code>EmergencyDataDTO</code>.
    * @alias module:model/EmergencyDataDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>EmergencyDataDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmergencyDataDTO} obj Optional instance to populate.
    * @return {module:model/EmergencyDataDTO} The populated <code>EmergencyDataDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmergencyDataDTO();

            
            
            

            if (data.hasOwnProperty('general')) {
                obj['general'] = GeneralDataDTO.constructFromObject(data['general']);
            }
            if (data.hasOwnProperty('hospitalizations')) {
                obj['hospitalizations'] = ApiClient.convertToType(data['hospitalizations'], [HospitalizationDTO]);
            }
            if (data.hasOwnProperty('lastMedicalCheck')) {
                obj['lastMedicalCheck'] = ApiClient.convertToType(data['lastMedicalCheck'], 'Date');
            }
            if (data.hasOwnProperty('medications')) {
                obj['medications'] = ApiClient.convertToType(data['medications'], [MedicationDTO]);
            }
            if (data.hasOwnProperty('pathologies')) {
                obj['pathologies'] = ApiClient.convertToType(data['pathologies'], [PathologyDTO]);
            }
            if (data.hasOwnProperty('surgeries')) {
                obj['surgeries'] = ApiClient.convertToType(data['surgeries'], [HospitalizationDTO]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/GeneralDataDTO} general
    */
    general = undefined;
    /**
    * @member {Array.<module:model/HospitalizationDTO>} hospitalizations
    */
    hospitalizations = undefined;
    /**
    * @member {Date} lastMedicalCheck
    */
    lastMedicalCheck = undefined;
    /**
    * @member {Array.<module:model/MedicationDTO>} medications
    */
    medications = undefined;
    /**
    * @member {Array.<module:model/PathologyDTO>} pathologies
    */
    pathologies = undefined;
    /**
    * @member {Array.<module:model/HospitalizationDTO>} surgeries
    */
    surgeries = undefined;








}


