/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The GeneralDataDTO model module.
* @module model/GeneralDataDTO
* @version 1.0.0
*/
export default class GeneralDataDTO {
    /**
    * Constructs a new <code>GeneralDataDTO</code>.
    * @alias module:model/GeneralDataDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>GeneralDataDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/GeneralDataDTO} obj Optional instance to populate.
    * @return {module:model/GeneralDataDTO} The populated <code>GeneralDataDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GeneralDataDTO();

            
            
            

            if (data.hasOwnProperty('allergic')) {
                obj['allergic'] = ApiClient.convertToType(data['allergic'], 'Boolean');
            }
            if (data.hasOwnProperty('allergies')) {
                obj['allergies'] = ApiClient.convertToType(data['allergies'], ['String']);
            }
            if (data.hasOwnProperty('bloodType')) {
                obj['bloodType'] = ApiClient.convertToType(data['bloodType'], 'String');
            }
            if (data.hasOwnProperty('organDonor')) {
                obj['organDonor'] = ApiClient.convertToType(data['organDonor'], 'Boolean');
            }
        }
        return obj;
    }

    /**
    * @member {Boolean} allergic
    */
    allergic = undefined;
    /**
    * @member {Array.<String>} allergies
    */
    allergies = undefined;
    /**
    * @member {String} bloodType
    */
    bloodType = undefined;
    /**
    * @member {Boolean} organDonor
    */
    organDonor = undefined;








}


