/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UserContactDTO from './UserContactDTO';





/**
* The UserProfileDTO model module.
* @module model/UserProfileDTO
* @version 1.0.0
*/
export default class UserProfileDTO {
    /**
    * Constructs a new <code>UserProfileDTO</code>.
    * @alias module:model/UserProfileDTO
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>UserProfileDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/UserProfileDTO} obj Optional instance to populate.
    * @return {module:model/UserProfileDTO} The populated <code>UserProfileDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserProfileDTO();

            
            
            

            if (data.hasOwnProperty('birthDate')) {
                obj['birthDate'] = ApiClient.convertToType(data['birthDate'], 'Date');
            }
            if (data.hasOwnProperty('contacts')) {
                obj['contacts'] = ApiClient.convertToType(data['contacts'], [UserContactDTO]);
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('idNumber')) {
                obj['idNumber'] = ApiClient.convertToType(data['idNumber'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('sex')) {
                obj['sex'] = ApiClient.convertToType(data['sex'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {Date} birthDate
    */
    birthDate = undefined;
    /**
    * @member {Array.<module:model/UserContactDTO>} contacts
    */
    contacts = undefined;
    /**
    * @member {String} firstName
    */
    firstName = undefined;
    /**
    * @member {String} idNumber
    */
    idNumber = undefined;
    /**
    * @member {String} lastName
    */
    lastName = undefined;
    /**
    * @member {String} sex
    */
    sex = undefined;








}


