/**
 * QR Emergencias WS
 * API Rest QR Emergencias
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EmergencyDataDTO from '../model/EmergencyDataDTO';

/**
* Emergencydatacontroller service.
* @module api/EmergencydatacontrollerApi
* @version 1.0.0
*/
export default class EmergencydatacontrollerApi {

    /**
    * Constructs a new EmergencydatacontrollerApi. 
    * @alias module:api/EmergencydatacontrollerApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * createEmergencyData
     * @param {module:model/EmergencyDataDTO} emergencyDataDTO emergencyDataDTO
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createEmergencyDataUsingPOSTWithHttpInfo(emergencyDataDTO) {
      let postBody = emergencyDataDTO;

      // verify the required parameter 'emergencyDataDTO' is set
      if (emergencyDataDTO === undefined || emergencyDataDTO === null) {
        throw new Error("Missing the required parameter 'emergencyDataDTO' when calling createEmergencyDataUsingPOST");
      }


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = null;

      return this.apiClient.callApi(
        '/api/emergencyData', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * createEmergencyData
     * @param {module:model/EmergencyDataDTO} emergencyDataDTO emergencyDataDTO
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createEmergencyDataUsingPOST(emergencyDataDTO) {
      return this.createEmergencyDataUsingPOSTWithHttpInfo(emergencyDataDTO)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * getEmergencyData
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/EmergencyDataDTO} and HTTP response
     */
    getEmergencyDataUsingGETWithHttpInfo() {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = EmergencyDataDTO;

      return this.apiClient.callApi(
        '/api/emergencyData', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * getEmergencyData
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/EmergencyDataDTO}
     */
    getEmergencyDataUsingGET() {
      return this.getEmergencyDataUsingGETWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
